server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/senanurcoban/config-servers
  profiles:
    active: dev